# Generated by Django 2.2.20 on 2021-05-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_boleta', models.DateField()),
                ('neto_boleta', models.IntegerField()),
                ('iva_boleta', models.IntegerField()),
                ('total_boleta', models.IntegerField()),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo_cliente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompraProveedor',
            fields=[
                ('id_compra', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
            ],
            options={
                'db_table': 'compra_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostoEnvio',
            fields=[
                ('id_costoenvio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'costo_envio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detalle', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_empleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres_empleado', models.CharField(max_length=50)),
                ('apellidos_empleado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50)),
                ('rut_empresa', models.CharField(max_length=10)),
                ('correo_empresa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoDespacho',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoRecepcion',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_recepcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateField()),
                ('neto_factura', models.IntegerField()),
                ('iva_factura', models.IntegerField()),
                ('total_factura', models.IntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id_familia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_familia', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'familia_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id_medio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'medio_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_compra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField()),
                ('descuento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_clp', models.IntegerField()),
                ('precio_usd', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('foto', models.BinaryField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
            ],
            options={
                'db_table': 'producto_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('rut_proveedor', models.CharField(max_length=10)),
                ('celular', models.BigIntegerField()),
                ('correo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecepcionProducto',
            fields=[
                ('id_recepcion', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recepcion_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumenProductos',
            fields=[
                ('id_respro', models.IntegerField(primary_key=True, serialize=False)),
                ('mes_anno', models.IntegerField()),
                ('id_producto', models.BigIntegerField()),
                ('nombre_producto', models.CharField(max_length=50)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('familia_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'resumen_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id_rubro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rubro', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rubro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCompra',
            fields=[
                ('id_tipocom', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipousu', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RubroProveedor',
            fields=[
                ('id_proveedor', models.OneToOneField(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Proveedor')),
            ],
            options={
                'db_table': 'rubro_proveedor',
                'managed': False,
            },
        ),
    ]
