# Generated by Django 2.2.20 on 2021-05-24 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210524_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_tipousu',
            field=models.ForeignKey(db_column='id_tipousu', default='01', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoUsuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.IntegerField(default='000', primary_key=True, serialize=False),
        ),
    ]
