# Generated by Django 2.2.20 on 2021-06-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210524_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familiaproducto',
            options={'ordering': ('nombre_familia',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('nombre_producto',)},
        ),
    ]
