# Generated by Django 2.2.20 on 2021-06-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210624_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True, 'ordering': ('nombre_producto',)},
        ),
        migrations.AddField(
            model_name='producto',
            name='id_familia',
            field=models.ForeignKey(db_column='id_familia', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.FamiliaProducto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoProducto'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='producto',
            index_together={('nombre_producto', 'id_tipo')},
        ),
    ]
