# Generated by Django 2.2.20 on 2021-06-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210624_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiaproducto',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_familia',
            field=models.ForeignKey(db_column='id_familia', on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='app.FamiliaProducto'),
        ),
        migrations.AlterIndexTogether(
            name='producto',
            index_together={('id_familia', 'slug')},
        ),
    ]
