# Generated by Django 2.2.20 on 2021-06-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210624_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familiaproducto',
            options={'managed': True, 'ordering': ('nombre_familia',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='familiaproducto',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
